language: node_js
node_js: 17
services:
  - postgresql
addons:
  postgresql: 13
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
env: 
  global:
  - PGPORT=5433
before_script:
  - psql -c 'create database matchdb;' -U postgres -p 5433
  - sudo -u postgres psql < fill_db.sql

before_install: cd ./cs3219-otot-taskb1-deployed/matching-service/
install: npm i
